# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20171030_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='login.User')),
                ('travelers', models.ManyToManyField(related_name='trips', to='login.User')),
            ],
        ),
    ]
