# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='desc',
        ),
    ]
